### ISSUE TITLE
Support Netlify forms spam prevention

### ISSUE THREAD

**Issue by evrardjp** [de-souza/hugo-flex#14]
Hello,

Do you think it would be nice to add a ``netlify:`` hash for the theme configuration, inside which there could be booleans to flip the reCAPTCHA/honeypot fields on/off in the netlify partial template?

See also: 
https://docs.netlify.com/forms/spam-filters/#extra-spam-prevention

**Comment by de-souza** [comment]
Hello,

I have added the possibility to enable a honeypot field and/or a recaptcha challenge on the contact form; unfortunately, when I enable the recaptcha challenge on my website, it won't display in the form and it will block all submissions. I don't understand why, because when I look at the HTML code it seems to contain the script from Google.

Does the recaptcha challenge work on your website? If not, I guess I will have to ask for help on the Netlify forums.

**Comment by evrardjp** [comment]
I didn't try recaptcha, I only used the honeypot field. I can check that when I am back from a business trip, but it will take 2 weeks. Sorry for the delay.

**Comment by de-souza** [comment]
I finally checked it and it works well :-) If the website uses a Content-Security-Policy, [ReCaptcha has to be allowed](https://developers.google.com/recaptcha/docs/faq#im-using-content-security-policy-csp-on-my-website.-how-can-i-configure-it-to-work-with-recaptcha) to load properly.
